Documentation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^snippets/', include('snippets.urls')),
    url(r'^docs/', include_docs_urls(title='Django Documentation/Jisan'))

]

main/urls.py
from django.conf.urls import url

from . import views
app_name = 'main'
urlpatterns = [
    # ex: /main/
    url(r'^$', views.IndexView.as_view(), name="index"),
    # ex: /main/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    # ex: /main/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
    # ex: /main/5/vote/
    url(r'^(?P<pk>[0-9]+)/vote/$', views.vote, name="vote")
]

main/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    OPTION_CHOICE = (
        ('E', "English"),
        ('M', "Medium"),
        ('B', "Bangla"),
    )
    pub_date = models.DateTimeField('date published')
    option_choice = models.CharField(max_length=1, choices=OPTION_CHOICE, default="null")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

main/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# from django.template import loader

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'main/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'main/results.html'


def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'main/detail.html',
                      {'question': question, 'error_message': "You didn't select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('main:results', args=(question.id,)))


"""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('main/index.html')
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'main/index.html', context)


def detail(request, question_id):
    # try:
    #    question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #    raise Http404("Question doesn't exists!")
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "main/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/results.html', {'question': question})

"""

main/templates/main/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <strong>
        {{ error_message }}
    </strong>
</p>
{% endif %}

<form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

main/templates/main/error404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eror 404</title>
</head>
<body>
<h1>Page not Found!!</h1>
</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Documentation</title>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
    <h1>Django Documentation</h1>
    <p>Analyzing django documentation!</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <h3>Demo Static Checking</h3>
            <img src="{% static 'main/images/book.jpg' %}" alt="." class="" width="250px" height="250px">
            <br>


        </div>
        <div class="col-sm-4">
            {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                <li><a href="{% url 'main:detail' question.id  %}">{{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No polls are available.</p>
            {% endif %}
        </div>

    </div>
</div>

</body>
</html>

main/templates/main/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'main:detail' question.id %}">Vote again?</a>